import json
from fastapi import APIRouter, HTTPException
from langchain_core.messages import HumanMessage

from app.models.request import AuditRequest
from app.models.response import AuditResponse
from app.agent.graph import auditor_agent

router = APIRouter(prefix="/api/v1")

@router.post("/audit", response_model=AuditResponse)
async def audit_policy(request: AuditRequest):
    """
    Accepts a user's policy details, triggers the LangGraph auditing agent, 
    and returns a structured JSON health score.
    """
    try:
        # 1. Initialize the graph state with the user's input
        initial_state = {
            "messages": [HumanMessage(content=request.user_query)]
        }
        
        # 2. Execute the LangGraph agent asynchronously.
        # This will spin through the LLM and the search tools until it finishes.
        final_state = await auditor_agent.ainvoke(initial_state)
        
        # 3. Extract the final response generated by the LLM
        last_message = final_state["messages"][-1].content
        
        # 4. Clean up Markdown formatting (LLMs often wrap JSON in ```json ... ```)
        cleaned_json_string = last_message.replace("```json", "").replace("```", "").strip()
        
        # 5. Parse the string into a dictionary
        score_data = json.loads(cleaned_json_string)
        
        # 6. Validate and return through the Pydantic model
        return AuditResponse(**score_data)

    except json.JSONDecodeError:
        raise HTTPException(
            status_code=500, 
            detail="The agent failed to format the response as valid JSON."
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))